### PR TITLE
Faster startup

### PR DESCRIPTION
**Pull request by PallHaraldsson**

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
Faster startup on Julia 1.5, I doubt slower after, but would have to test there, as has no effect on old versions.

**Comment by zachmatson** [comment]
I don't think there is much room for optimization with this module, and it is pretty much only useful in the context of scripts, so this seems like a good idea. A few questions though:

1. In [this post](https://discourse.julialang.org/t/precompile-a-script/5364/10) you're getting 0.32 seconds for just loading the module, but after the module has been precompiled I'm getting startup times about an order of magnitude less than this anyways. Is this consistent behavior when you're running it? Is there something special with that setup and Julia 1.5 vs 1.4 that slows it down?
2. Any reason to go with `O1` instead of `O0`?

**Comment by PallHaraldsson** [comment]
I timed and -O1 seemed as fast as -o0 so I was just conservative, while for this package -O0 would have been a good candidate (in general you want to be cautious to not go too low).

You are probably seeing something like (and Julia 1.5 only is optimizes for the added code):

```
julia> @time using ArgParse
[ Info: Precompiling ArgParse [c7e460c6-2fb9-53a9-8c5b-16f535851c63]
  2.160035 seconds (988.78 k allocations: 47.572 MiB, 0.39% gc time)

julia> @time using ArgParse
  0.000269 seconds (196 allocations: 10.797 KiB)

but you need to exit as, second using (and sometimes even third) is faster:

$ ~/julia-1.4.0/bin/julia 
julia> @time using ArgParse
  1.028406 seconds (1.27 M allocations: 60.405 MiB, 1.02% gc time)

julia> @time using ArgParse
  0.000258 seconds (196 allocations: 10.797 KiB)
```

**Comment by zachmatson** [comment]
Considering also your [latest update on that Julia Discourse thread](https://discourse.julialang.org/t/precompile-a-script/5364/12) and the results above, if this optimization really only makes a difference on an old nightly of 1.5, where 1.4 and 1.6 are both performing fine without this, and it seems that there's not much reason for people to stick with 1.5 anyways once 1.6 comes out, I'm going to close this PR for now. Once 1.5 stable is out I'll see if this lower optimization level makes enough of a difference still.

**Comment by PallHaraldsson** [comment]
At least know this is still valuable trick, even for 1.6, for some packages like Revise.jl where my identical PR was just merged. And it even still has 6 sec startup on 1.6.

You are going to check on final 1.5, so I would consider reopening, so you don't forget. And 1.6 could still get slower. It's far from released, and while we should hope they try to keep all gains so far, they might opt for more, thus slower optimization.

**Comment by zachmatson** [comment]
image

These are my results with 1.4.1 (still need to upgrade to 1.4.2) and 1.5.0-beta1.0. Based on this, I'm still not seeing much of a startup time issue. Any script using Julia right now is realistically going to make this amount of time insignificant. Cannot reopen now either because the branch was deleted, but it looks like the files are still available. Not sure how to properly give you credit if I end up adding your code back in manually though.

**Comment by PallHaraldsson** [comment]
I thought you liked to know, that I can get (824.6-154.6)/(214.4-154.6) = 11x faster on just your code (3.8x faster if you include Julia's startup of ) on just your code, using `--compile=min` I rediscovered. Yes, absolute time difference is not large just over half a sec. but this is minimal code, and such differences add up.

```
$ hyperfine '~/julia-1.6.0-DEV-8f512f3f6d/bin/julia -O0 --compile=min --startup-file=no argtest.jl 5 6 7'
Benchmark #1: ~/julia-1.6.0-DEV-8f512f3f6d/bin/julia -O0 --compile=min --startup-file=no argtest.jl 5 6 7
  Time (mean ± σ):     232.6 ms ±  32.5 ms    [User: 420.4 ms, System: 288.1 ms]
  Range (min … max):   214.4 ms … 322.0 ms    10 runs

$ hyperfine '~/julia-1.6.0-DEV-8f512f3f6d/bin/julia --startup-file=no argtest.jl 5 6 7'
Benchmark #1: ~/julia-1.6.0-DEV-8f512f3f6d/bin/julia --startup-file=no argtest.jl 5 6 7
  Time (mean ± σ):     893.5 ms ±  37.8 ms    [User: 1.248 s, System: 0.528 s]
  Range (min … max):   824.6 ms … 953.3 ms    10 runs

$ cat argtest.jl
using ArgMacros

function main()
    @beginarguments begin
        @positionalrequired Int x
        @positionaldefault Int 5 y
        @positionaloptional Int z
    end

    println(x + y) # Prints x + y, the variable names are available right away and must be Ints
    println(isnothing(z)) # z might be nothing, because it was optional
    z = nothing # It is fine to store values of type Nothing or Int in z now
    z = 8
#    x = 5.5 # Raises an error, x must hold Int values
#    y = nothing # Raises an error, only optional arguments can hold nothing
end

main()
```

Also the (currently undocumented) `--compile=min` option, can't be added selectively to packages. And yes, the time difference of `using ArgMacros` only is unchanged (or very little change), and I'm not sure this option would help your users if possible to apply selectively to the package (I opened an issue on Julia's github for it, and Jeff wrote we should add the option), and your users wouldn't ask for it.

**Comment by zachmatson** [comment]
After trying this out and looking at this example, I see your point. I am going to add this code to the package. Thank you!

**Pull request closed without merging**
